In [23]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf

# QUESTION 1 (3 pts):

### What is the main benefit of neural network based predictive models over traditional symbolic machine learning models such as decision trees for example?
### What is it that a “deep” neural network can do that a “shallow” (3 layer input-hidden-output) cannot do?


with neural network based predictive models we can build models of more complexity to more accurately learn and predict from the data. With traditional symbolic machine learning models we cannot build as complex of a model to do predictions on datasets with many variables.typically the more complex a dataset is, the better it is to utilize NN models in order to getter better and more accurate predictions. However, it could be costly, therefore, traditional symbolic machine learning models are still very important as there are still problems that can be solved using ml models like decision tree that would be far less expensive.


Deep neural network can take in account more complexity than shallow neural network models. For instance, a deep neural network will typically have many more hidden layers in the hidden part of the architecture where each hidden layer will be able to understand and learn a specific part of the dataset (like a straight line and a curved line difference in a CNN model). However, shallow neural network models that consist of fewer hidden layers in the hidden part of the architecture will be only dealing with calculating much more straight forward when it comes to the weights. and they are mainly used for less complex problems that need to be solved (complexity != importance). for instance, shallow NN can be more cost and time efficient and some problems that need to be solved are not so complicated like a picture to be recognized (it could be maybe bank account and habit spendings of a person that the model needs to predict with high accuracy whether the person is worthy of a certain loan or not)

# QUESTION 2 (3 pts):

## For approximately the same number of neurons, is it “better” to have a shallow (e.g. three layer) neural network with many nodes per layer, or is it “better” to have more layers of neurons, but fewer neurons per layer? That is, for example, can you keep one hidden layer of 200 neurons, or three hidden layers of say, 50, 100, and 50 neurons (also adding up to 200). Use the housing dataset (predicting ocean_proximity) and MLP classifiers (not keras) to answer this question. You do not need to go with 200, I justed used that as an example to illustrate the question.

In [7]:
housing = pd.read_csv('housing.csv')

In [8]:
np.unique(housing['ocean_proximity'])

array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
      dtype=object)

In [9]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [10]:
housing.dropna(axis = 0, inplace= True)

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [12]:
housing.iloc[:, 0:9]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  
0           322.0       126.0         8.3252            452600.0  
1          2401.0      1138.0         8.3014            358500.0  
2           496.0       177.0         7.2574            352100.0  
3           558.0       219.0         5.6431            341300.0  
4           565.0       259.0         3.8462            342200.0  
...           ...         ...            ...                 ...  
20635       845.0       330.0         1.5603             78100.0  
20636       356.0       114.0         2.5568             77100.0  
20637      1007.0       433.0         1.7000             92300.0  
20638       741.0       349.0         1.8672             84700.0  
20639      1387.0       530.0         2.3886             89400.0  

[20433 rows x 9 columns]

In [13]:
X = housing.iloc[:, 0:9]
y = housing['ocean_proximity']

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder

In [15]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [16]:
X_scaled

array([[-1.32731375,  1.05171726,  0.98216331, ..., -0.97683327,
         2.34516291,  2.12881864],
       [-1.32232256,  1.04235526, -0.60621017, ...,  1.67037262,
         2.33263161,  1.31362603],
       [-1.33230494,  1.03767426,  1.85576873, ..., -0.84342665,
         1.78293943,  1.25818254],
       ...,
       [-0.82320322,  1.77727236, -0.92388486, ..., -0.17377773,
        -1.14317103, -0.99247676],
       [-0.87311515,  1.77727236, -0.84446619, ..., -0.39350628,
        -1.05513604, -1.05831591],
       [-0.83318561,  1.74918635, -1.00330353, ...,  0.07995643,
        -0.78060586, -1.01759959]])

In [17]:
y = np.array(y)

In [18]:
scaler = OrdinalEncoder()
y_scaled = scaler.fit_transform(y.reshape(-1,1))

In [19]:
y_scaled

array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [1.],
       [1.]])

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size= 0.2, random_state= 1)

In [21]:
## Shallow

mlp_clf = MLPClassifier(hidden_layer_sizes= (200,), max_iter=250, solver='adam', learning_rate='adaptive')
mlp_clf.fit(X_train, y_train)
shallow_prediction = mlp_clf.predict(X_test)
print(confusion_matrix(y_test, shallow_prediction))
print(accuracy_score(y_test, shallow_prediction))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[1665   27    0   35   75]
 [  40 1265    0    3    0]
 [   0    0    0    0    2]
 [   9    2    0  415   14]
 [  93    0    0   12  430]]
0.923660386591632


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [22]:
## less Shallow

mlp_clf = MLPClassifier(hidden_layer_sizes= (50,100,50,), max_iter=250, solver='adam', learning_rate='adaptive')
mlp_clf.fit(X_train, y_train)
less_shallow_prediction = mlp_clf.predict(X_test)
print(confusion_matrix(y_test, less_shallow_prediction))
print(accuracy_score(y_test, less_shallow_prediction))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[1735   18    0    2   47]
 [  30 1278    0    0    0]
 [   0    0    0    0    2]
 [  15    2    0  407   16]
 [  80    0    0    6  449]]
0.9466601419133839


#### Better accuracy score with multiple hidden layers of 200 nodes total compared to 1 layer and 200 nodes in that one.

# QUESTION 3 (4 pts):

## Also using the housing dataset, but this time using keras, answer two questions: (a) do different activation functions make a difference and (b) do different “optimizers” make a difference? In each case compare 2 options on a test set (using any keras architecture you choose to determine (a) which activation function appears to help build the best model and (b) which optimizer helps build the best model.You can fix the architecture and the test set across runs, and comparing these results across a single run is perfectly reasonable.

In [24]:
from tensorflow import keras

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [26]:
np.random.seed(42)

## a)
## Optimizer sgd
## Activation Function ReLU

In [27]:
model = Sequential()

model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(5, activation='softmax'))

In [28]:
sgd = keras.optimizers.SGD(lr=0.05)
model.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [29]:
model.fit(X_train, y_train, epochs=100, batch_size=100)

Epoch 1/100
164/164 [==============================] - 2s 3ms/step - loss: 1.0068 - accuracy: 0.6278
Epoch 2/100
164/164 [==============================] - 0s 2ms/step - loss: 0.6443 - accuracy: 0.7603
Epoch 3/100
164/164 [==============================] - 0s 2ms/step - loss: 0.5298 - accuracy: 0.7924
Epoch 4/100
164/164 [==============================] - 0s 2ms/step - loss: 0.4392 - accuracy: 0.8259
Epoch 5/100
164/164 [==============================] - 0s 2ms/step - loss: 0.3887 - accuracy: 0.8452
Epoch 6/100
164/164 [==============================] - 0s 2ms/step - loss: 0.3718 - accuracy: 0.8506
Epoch 7/100
164/164 [==============================] - 0s 2ms/step - loss: 0.3425 - accuracy: 0.8574
Epoch 8/100
164/164 [==============================] - 0s 2ms/step - loss: 0.3385 - accuracy: 0.8611
Epoch 9/100
164/164 [==============================] - 0s 2ms/step - loss: 0.3233 - accuracy: 0.8681
Epoch 10/100
164/164 [==============================] - 0s 2ms/step - loss: 0.3106 - accura

In [30]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

128/128 [==============================] - 1s 4ms/step - loss: 0.1718 - accuracy: 0.9320

accuracy: 93.20%


## a)
## Optimizer sgd
## Activation Function Sigmoid

In [31]:
model = Sequential()

model.add(Dense(50, input_dim=9, activation='sigmoid'))
model.add(Dense(100, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(5, activation='softmax'))

In [32]:
sgd = keras.optimizers.SGD(lr=0.05)
model.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [33]:
model.fit(X_train, y_train, epochs=100, batch_size=100)

Epoch 1/100
164/164 [==============================] - 1s 2ms/step - loss: 1.2465 - accuracy: 0.4399
Epoch 2/100
164/164 [==============================] - 0s 2ms/step - loss: 1.2312 - accuracy: 0.4424
Epoch 3/100
164/164 [==============================] - 0s 2ms/step - loss: 1.2241 - accuracy: 0.4424
Epoch 4/100
164/164 [==============================] - 0s 2ms/step - loss: 1.2167 - accuracy: 0.4440
Epoch 5/100
164/164 [==============================] - 0s 2ms/step - loss: 1.2058 - accuracy: 0.4521
Epoch 6/100
164/164 [==============================] - 0s 2ms/step - loss: 1.1905 - accuracy: 0.4777
Epoch 7/100
164/164 [==============================] - 0s 2ms/step - loss: 1.1641 - accuracy: 0.5418
Epoch 8/100
164/164 [==============================] - 0s 2ms/step - loss: 1.1254 - accuracy: 0.5931
Epoch 9/100
164/164 [==============================] - 0s 2ms/step - loss: 1.0798 - accuracy: 0.6044
Epoch 10/100
164/164 [==============================] - 0s 2ms/step - loss: 1.0371 - accura

In [34]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

128/128 [==============================] - 1s 3ms/step - loss: 0.3277 - accuracy: 0.8515

accuracy: 85.15%


## b)
## Optimizer Adam
## Activation Function ReLU

In [35]:
model = Sequential()

model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(5, activation='softmax'))

In [36]:
adam = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, decay=0.0, amsgrad=False)
model.compile(loss='sparse_categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [37]:
model.fit(X_train, y_train, epochs=100, batch_size=100)

Epoch 1/100
164/164 [==============================] - 1s 3ms/step - loss: 0.7952 - accuracy: 0.7084
Epoch 2/100
164/164 [==============================] - 0s 3ms/step - loss: 0.4979 - accuracy: 0.8064
Epoch 3/100
164/164 [==============================] - 0s 3ms/step - loss: 0.3855 - accuracy: 0.8466
Epoch 4/100
164/164 [==============================] - 0s 3ms/step - loss: 0.3422 - accuracy: 0.8586
Epoch 5/100
164/164 [==============================] - 0s 2ms/step - loss: 0.3158 - accuracy: 0.8718
Epoch 6/100
164/164 [==============================] - 0s 3ms/step - loss: 0.2975 - accuracy: 0.8784
Epoch 7/100
164/164 [==============================] - 0s 3ms/step - loss: 0.2877 - accuracy: 0.8840
Epoch 8/100
164/164 [==============================] - 0s 3ms/step - loss: 0.2679 - accuracy: 0.8925
Epoch 9/100
164/164 [==============================] - 0s 3ms/step - loss: 0.2601 - accuracy: 0.8943
Epoch 10/100
164/164 [==============================] - 0s 3ms/step - loss: 0.2458 - accura

In [38]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

128/128 [==============================] - 0s 2ms/step - loss: 0.1714 - accuracy: 0.9383

accuracy: 93.83%


## b)
## Optimizer Adam
## Activation Function Sigmoid

In [39]:
model = Sequential()

model.add(Dense(50, input_dim=9, activation='sigmoid'))
model.add(Dense(100, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(5, activation='softmax'))

In [40]:
adam = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, decay=0.0, amsgrad=False)
model.compile(loss='sparse_categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

In [41]:
model.fit(X_train, y_train, epochs=100, batch_size=100)

Epoch 1/100
164/164 [==============================] - 1s 5ms/step - loss: 1.2337 - accuracy: 0.4730
Epoch 2/100
164/164 [==============================] - 0s 3ms/step - loss: 0.9420 - accuracy: 0.6400
Epoch 3/100
164/164 [==============================] - 0s 3ms/step - loss: 0.7496 - accuracy: 0.7317
Epoch 4/100
164/164 [==============================] - 0s 3ms/step - loss: 0.6665 - accuracy: 0.7619
Epoch 5/100
164/164 [==============================] - 0s 3ms/step - loss: 0.6203 - accuracy: 0.7744
Epoch 6/100
164/164 [==============================] - 0s 3ms/step - loss: 0.5784 - accuracy: 0.7809
Epoch 7/100
164/164 [==============================] - 1s 5ms/step - loss: 0.5323 - accuracy: 0.7894
Epoch 8/100
164/164 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.8033
Epoch 9/100
164/164 [==============================] - 0s 3ms/step - loss: 0.4413 - accuracy: 0.8288
Epoch 10/100
164/164 [==============================] - 0s 3ms/step - loss: 0.4100 - accura

In [42]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

128/128 [==============================] - 0s 2ms/step - loss: 0.1666 - accuracy: 0.9290

accuracy: 92.90%


From all, Optimizer adam with activation function relu did the best and had the highest accuracy.

sgd optimizer and af sigmoid had the worst accuracy out of all.